name: Python test workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: Test python
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: pytest testing
      run: |
        pytest tests
        
    - name: pytest coverage
      run:
        pytest --cov=./src --cov-report=xml:tests/coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3